### ISSUE TITLE
Donated in some one elses name and got an error?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1211]
Donation worked... not sure why the error happened
<img width="1109" alt="Screen Shot 2020-04-17 at 4 21 47 PM" src="https://user-images.githubusercontent.com/14945613/79579290-ad25bc00-80c7-11ea-887b-113507b960d9.png">

Issue type: **Error**
Something went wrong with your donation. Could not approve token allowance.

**Name:**
Cannot read property 'on' of undefined

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

TypeError: Cannot read property 'on' of undefined
    at t.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/60749b228bd0de734fb74f8850ab8fd67f09e4d8/static/js/main.f06c67b5.js:1:610292)
    at _ (https://d33wubrfki0l68.cloudfront.net/js/60749b228bd0de734fb74f8850ab8fd67f09e4d8/static/js/main.f06c67b5.js:1:2413507)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/60749b228bd0de734fb74f8850ab8fd67f09e4d8/static/js/main.f06c67b5.js:1:2413295)
    at Generator.e.<computed> [as throw] (https://d33wubrfki0l68.cloudfront.net/js/60749b228bd0de734fb74f8850ab8fd67f09e4d8/static/js/main.f06c67b5.js:1:2413686)
    at r (https://d33wubrfki0l68.cloudfront.net/js/60749b228bd0de734fb74f8850ab8fd67f09e4d8/static/js/main.f06c67b5.js:1:602924)
    at https://d33wubrfki0l68.cloudfront.net/js/60749b228bd0de734fb74f8850ab8fd67f09e4d8/static/js/main.f06c67b5.js:1:603043
</details>

**Comment by GriffGreen** [comment]
Same Error again
<img width="864" alt="Screen Shot 2020-04-17 at 4 41 09 PM" src="https://user-images.githubusercontent.com/14945613/79581123-46ee6880-80ca-11ea-8c8a-1583147e451f.png">

**Comment by GriffGreen** [comment]
Another
<img width="1110" alt="Screen Shot 2020-04-17 at 4 57 50 PM" src="https://user-images.githubusercontent.com/14945613/79582887-abaac280-80cc-11ea-98a8-dde9552eab01.png">

**Comment by GriffGreen** [comment]
Ooooooo! A Hint!!!

I donated in the name of a user that has an account on Giveth already: 0x1dba1131000664b884a1ba238464159892252d3a

and everything worked out like it should

**Comment by GriffGreen** [comment]
Ok it didnt happen again with this address:
0x5e91a95f9ce92c66f2b31261d92ff6d3d08a05e4

But then it did with this one: 
<img width="1134" alt="Screen Shot 2020-04-17 at 5 12 24 PM" src="https://user-images.githubusercontent.com/14945613/79587182-6b4e4300-80d2-11ea-865b-721a9b2efba6.png">
