### ISSUE TITLE
Can't Donate! Oh no!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1246]
Issue type: **Error**
Something went wrong with your donation. Could not approve token allowance.

**Name:**
[number-to-bn] while converting number "7.767421000000000276486e+21" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

Error: [number-to-bn] while converting number "7.767421000000000276486e+21" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.
    at e.exports (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:482606)
    at Object.fromWei (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:536439)
    at Object.fromWei (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:271659)
    at Function.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:385606)
    at _ (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:2420961)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:2420749)
    at Generator.e.<computed> [as next] (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:2421140)
    at r (https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:374085)
    at https://d33wubrfki0l68.cloudfront.net/js/96418fd0d0afedbc2f8b3ea87d9c25562abb0fba/static/js/main.98863784.js:1:374179
</details>

**Comment by GriffGreen** [comment]
<img width="876" alt="Screen Shot 2020-05-08 at 1 23 52 AM" src="https://user-images.githubusercontent.com/14945613/81353950-ad174b80-90ca-11ea-92b5-a89c7e8804d2.png">

**Comment by GriffGreen** [comment]
Ok so it is for sure just a weird big number error... I can donate 999 but can't donate 1000
<img width="812" alt="Screen Shot 2020-05-08 at 1 34 42 AM" src="https://user-images.githubusercontent.com/14945613/81354548-3713e400-90cc-11ea-85d3-b73098233fdf.png">

<img width="713" alt="Screen Shot 2020-05-08 at 1 35 52 AM" src="https://user-images.githubusercontent.com/14945613/81354588-501c9500-90cc-11ea-8d3e-4bcf80074a1d.png">

**Comment by aminlatifi** [comment]
It should be fixed now
