### ISSUE TITLE
Dapp went down on monday

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1482]
I went to: 
https://beta.giveth.io/profile/0x85671e16e36cAB63b94d318A2a17738e7d1CF958

I changed the networks around still no dice

<img width="1261" alt="Screen Shot 2020-10-19 at 10 20 57 PM" src="https://user-images.githubusercontent.com/14945613/96507446-76d51f00-1259-11eb-91d2-23b58a27caeb.png">

Then i realized its the whole dapp

<img width="1273" alt="Screen Shot 2020-10-19 at 10 28 41 PM" src="https://user-images.githubusercontent.com/14945613/96508229-8dc84100-125a-11eb-842e-4f173783961b.png">

**Comment by aminlatifi** [comment]
Feathers couldn't connect to DB... fixed after restarting feathers service.

```
2020-10-19 20:26: { Error: connection 72 to giveth-prod-shard-00-02-r4scu.gcp.mongodb.net:27017 timed out
2020-10-19 20:26:     at TLSSocket.<anonymous> (/home/deploy/feathers-giveth-beta/node_modules/mongodb-core/lib/connection/connection.js:258:7)
2020-10-19 20:26:     at Object.onceWrapper (events.js:314:30)
2020-10-19 20:26:     at emitNone (events.js:105:13)
2020-10-19 20:26:     at TLSSocket.emit (events.js:207:7)
2020-10-19 20:26:     at TLSSocket.Socket._onTimeout (net.js:400:8)
2020-10-19 20:26:     at ontimeout (timers.js:471:11)
2020-10-19 20:26:     at tryOnTimeout (timers.js:306:5)
2020-10-19 20:26:     at Timer.listOnTimeout (timers.js:266:5)
2020-10-19 20:26:   message: 'connection 72 to giveth-prod-shard-00-02-r4scu.gcp.mongodb.net:27017 timed out',
2020-10-19 20:26:   level: 'error',
2020-10-19 20:26:   timestamp: '2020-10-19T20:26:20.116Z',
2020-10-19 20:26:   [Symbol(level)]: 'error',
2020-10-19 20:26:   [Symbol(message)]: '{"message":"connection 72 to giveth-prod-shard-00-02-r4scu.gcp.mongodb.net:27017 timed out","level":"error","timestamp":"2020-10-19T20:26:20.116Z"}' }
```

Maybe we should monitor the websocket connection to mongo as we do for connection to ethereum node (web3).
