### ISSUE TITLE
Weird issue, was delegating to milestones and now the campaign won't load

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1648]
Issue type: **Error**
Sadly we were unable to get the exchange rate! Please try again after refresh.

**Name:**
user is not allowed to do action [find] on [giveth.conversionrates]

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"Error: user is not allowed to do action [find] on [giveth.conversionrates]\n    at convert (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:135418)\n    at r.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2242910)\n    at r.onack (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2317144)\n    at r.onpacket (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2316550)\n    at r.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2318588)\n    at r.emit (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2270949)\n    at r.ondecoded (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2276670)\n    at o.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2318588)\n    at o.r.emit (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2270949)\n    at o.add (https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2263669)"
</details>

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e

<img width="645" alt="Screen Shot 2021-01-07 at 7 48 27 PM" src="https://user-images.githubusercontent.com/14945613/103960921-a65a4000-5153-11eb-9cab-162c9aeb8322.png">
