### ISSUE TITLE
Made a Milestone, now I can't connect to feathers, Can't access the website... can't pay people :-(

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1725]
SO WEIRD! i made a Milestone today, proposed it... and now the DApp wont load!

It works on my chrome browser that i never use... but on Brave, where I have my keys... i can't get it to load... i killed metamask and cleared my cache (not cookies tho) and it still won't load

Brave:
<img width="534" alt="Screen Shot 2021-02-02 at 12 46 53 PM" src="https://user-images.githubusercontent.com/14945613/106641071-17401c80-6587-11eb-911c-0fe02569029a.png">

<img width="1423" alt="Screen Shot 2021-02-02 at 12 45 35 PM" src="https://user-images.githubusercontent.com/14945613/106641077-1909e000-6587-11eb-86a7-c248763e571e.png">

Chrome:
<img width="1269" alt="Screen Shot 2021-02-02 at 12 47 52 PM" src="https://user-images.githubusercontent.com/14945613/106641191-363eae80-6587-11eb-8e3a-66ccea692735.png">

**Comment by aminlatifi** [comment]
I restarted the beta feathers server and it fixed. 
It's the feathers log before restarting which can be related to this issue:
```
2021-02-02 19:07: info: current "NewEventQueue" QUEUE -> isProcessing: true -> status: [
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null,
2021-02-02 19:07:   null
2021-02-02 19:07: ] 
```

**Comment by aminlatifi** [comment]
And this in error few hours ago:
```
2021-02-01 15:54: { MethodNotAllowed: Can not remove multiple entries
2021-02-01 15:54:     at new MethodNotAllowed (/home/deploy/feathers-giveth-beta/node_modules/@feathersjs/adapter-commons/node_modules/@feathersjs/errors/lib/index.js:121:17)
2021-02-01 15:54:     at Object.remove (/home/deploy/feathers-giveth-beta/node_modules/@feathersjs/adapter-commons/lib/service.js:88:35)
2021-02-01 15:54:     at processHooks.call.then.hookObject (/home/deploy/feathers-giveth-beta/node_modules/@feathersjs/feathers/lib/hooks.js:65:27)
2021-02-01 15:54:     at process._tickCallback (internal/process/next_tick.js:68:7)
2021-02-01 15:54:   type: 'FeathersError',
2021-02-01 15:54:   name: 'MethodNotAllowed',
2021-02-01 15:54:   message: 'Can not remove multiple entries',
2021-02-01 15:54:   code: 405,
2021-02-01 15:54:   className: 'method-not-allowed',
2021-02-01 15:54:   data: undefined,
2021-02-01 15:54:   errors: {} }
```

**Comment by aminlatifi** [comment]
I reverted socket.io PRs in both feathers and dapp, the major suspect. Let's merge it in next release to beta and see what happens

**Comment by aminlatifi** [comment]
No occurrence for a while

**Comment by aminlatifi** [comment]
> I reverted socket.io PRs in both feathers and dapp, the major suspect. Let's merge it in next release to beta and see what happens

It wasn't helpful
