### ISSUE TITLE
can't edit a proposed milestone

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#233]
**Expected Behavior:**

I should be able to edit a proposed milestone.

**Current Behavior:**

When I try and edit it hangs (fails). The feathers logs show that the milestone is being accepted.

```
0|feathers | 2018-01-19 21:01: info: error: milestones - Method: patch: Only the campaign owner can accept a milestone
0|feathers | 2018-01-19 21:01: warn:  Forbidden: Only the campaign owner can accept a milestone
0|feathers |     at new Forbidden (/home/deploy/feathers-giveth/node_modules/feathers-errors/lib/index.js:114:17)
0|feathers |     at canUpdate (/home/deploy/feathers-giveth/build/services/milestones/milestones.hooks.js:95:17)
0|feathers |     at /home/deploy/feathers-giveth/build/services/milestones/milestones.hooks.js:121:74
0|feathers |     at <anonymous>
```

I suspect this is a dapp bug, but could be a bug in feathers-giveth repo

**Comment by perissology** [comment]
feathers bug. fixed in https://github.com/Giveth/feathers-giveth/commit/9fc755f52451a768dbec36212d4e88afa6269108
