### ISSUE TITLE
I think this is a false error... you would know Amin ;-)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2358]
Issue type: **Error**
Unable to update the donation in feathers

**Name:**
Error

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"NotAuthenticated: Error\n    at new c (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:3094030)\n    at convert (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:3096058)\n    at p.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:3087341)\n    at p.onack (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:1384756)\n    at p.onpacket (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:1384161)\n    at p.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:1386097)\n    at p.r.emit (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:603725)\n    at p.ondecoded (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:1375629)\n    at l.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:1386097)\n    at l.r.emit (https://d33wubrfki0l68.cloudfront.net/bundles/76e5ab000916e0d5d33a8ae27d3275a13ffbe046.js:2:603725)"
</details>

<img width="1259" alt="Screen Shot 2021-07-11 at 12 00 07 AM" src="https://user-images.githubusercontent.com/14945613/125177310-08673100-e1db-11eb-86bb-cda75e15c739.png">

https://trace.giveth.io/trace/amin-reg-rewards-june-8-july-5

**Comment by MoeNick** [comment]
Needs more clarification.

**Comment by aminlatifi** [comment]
Probably brave connection issue with feathers is the root cause

**Comment by aminlatifi** [comment]
#2357

**Comment by aminlatifi** [comment]
@RamRamez Please add more smooth error handling

**Comment by RamRamez** [comment]
> @RamRamez Please add more smooth error handling

I changed that terrible error modal to a toast error PR #2479

**Comment by divine-comedian** [comment]
how can this issue bes tested?

**Comment by RamRamez** [comment]
> how can this issue be tested?

The error is shown when there are some problems with connecting to the backend.
@aminlatifi Could you help on testing this issue?
