### ISSUE TITLE
Something went wrong on getting user Traces!

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2451]
Issue type: **Error**
Something went wrong on getting user Traces!

**Name:**
jwt expired

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"NotAuthenticated: jwt expired\n    at new c (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:2706978)\n    at convert (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:2709006)\n    at p.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:2700293)\n    at p.onack (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:1408823)\n    at p.onpacket (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:1408228)\n    at p.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:1410164)\n    at p.r.emit (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:635891)\n    at p.ondecoded (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:1399701)\n    at l.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:1410164)\n    at l.r.emit (https://d33wubrfki0l68.cloudfront.net/bundles/00d5e02d2029816f996994b30183c54ad12a13c0.js:2:635891)"
</details>

**Comment by RamRamez** [comment]
Added smooth ErrorHandler PR #2481

**Comment by divine-comedian** [comment]
How can this issue be tested?

**Comment by RamRamez** [comment]
> How can this issue be tested?

@aminlatifi can help us.
