### ISSUE TITLE
Errors delegating to Traces 

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#2556]
Receiving errors when delegating funds to Traces - this one on paying Amins Trace on Giveth 2 Campaign.

Issue type: **Error**
Unable to update the donation in feathers

**Name:**
Error

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"NotAuthenticated: Error\n    at new c (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:2531672)\n    at convert (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:2533700)\n    at p.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:2524987)\n    at p.onack (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:1337452)\n    at p.onpacket (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:1336857)\n    at p.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:1338793)\n    at p.r.emit (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:624669)\n    at p.ondecoded (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:1328330)\n    at l.<anonymous> (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:1338793)\n    at l.r.emit (https://d33wubrfki0l68.cloudfront.net/bundles/0a08adf3c01a13e5279cc943c2ec2023df978ba3.js:2:624669)"
</details>

**Comment by Danibelle** [comment]
Popups are stacked on top of the Delegation window, which I then have to close.  I don't know if I really got an error, the transaction really went through, if I should just close out the Delegation window or do it again:

![image](https://user-images.githubusercontent.com/39466970/135755445-a349a87a-6717-4d65-b3cd-1f333aedd987.png)

![image](https://user-images.githubusercontent.com/39466970/135755458-6f800e6d-c544-4f26-8a07-612c759fb86d.png)

![image](https://user-images.githubusercontent.com/39466970/135755471-3c0a4a9d-dffd-482e-b508-990f6cbaeaad.png)

**Comment by Danibelle** [comment]
Sometimes there is a "Transaction Failed" in the stack of errors.. then after I close them all out I get a "Transaction Successful!"

![image](https://user-images.githubusercontent.com/39466970/135755629-ec9fd031-620a-48a0-a10d-e114a70a8294.png)

**Comment by MoeNick** [comment]
@RamRamez cam you please investigate?

**Comment by aminlatifi** [comment]
This issue is somehow complicated. Basically DApp prepares transactions (here delegation) based on pledges data stored in backend. On @Danibelle first delegation, she couldn't send updated data to feathers so the pledges data were obsolete. 
So next delegation attempt was created based on that obsolete data, that's the reason the smart contract rejected the call since probably the intended pledges had not enough money inside to pay.

No easy fix comes to my mind at this moment, the only working solution I would recommend is that after delegating on project money (Here the campaign), user should wait for about 10 blocks of rinkeby to be mined before next attempt to delegating from same project.

**Comment by Danibelle** [comment]
OK Thank you Amin.

I understand this from subsequent delegations - the difference between the first delegation (yours) and subsequent delegations is that there were TWO "Oh No" messages instead of just one.

But the bigger issue is that instantly upon signing the MetaMask transaction - all the errors popped up instantly.
An "Oh No"..
With a "Transaction Failed" beneath it..
and the Delegation window remained open below it.

Seems like there should be a delay after signing that says WAIT ... and the Delegation Window should either close when I select Delegate, or stay in a waiting stage until the blocks are mined.

**Comment by Danibelle** [comment]
I do get a 'Transaction Successful' once the blocks are mined.

**Comment by aminlatifi** [comment]
In DM also @Danibelle mentioned an important clue! The first delegation was not complete!
To explain more, a trace needed 1.39 ETH but at the first delegation 1.2 ETH was delegated. So my assumption about obsolete state can not be the reason in this case.
