### ISSUE TITLE
Can't approve or accept any milestone...

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#300]
I can't seem to move milestones along tonight... not sure whats up.

Obv i have logged in and logged out several times and all these things.

<img width="1302" alt="screen shot 2018-04-13 at 2 20 30 am" src="https://user-images.githubusercontent.com/14945613/38710603-8a460766-3ec1-11e8-8ecb-d30f6b936267.png">

Copy Paste of the error:

index.js:213 connection not open on send()
o.send @ index.js:213
value @ WebSocketSubProvider.js:33
t @ index.js:113
l.handleRequest @ hooked-wallet.js:197
t @ index.js:113
value @ GasPriceProvider.js:17
t @ index.js:113
handleRequest @ inflight-cache.js:30
t @ index.js:113
c.handleRequest @ filters.js:88
t @ index.js:113
o.handleRequest @ sanitizer.js:27
t @ index.js:113
s.handleRequest @ nonce-tracker.js:79
t @ index.js:113
r.handleRequest @ fixture.js:26
t @ index.js:113
value @ CleanserSubProvider.js:16
t @ index.js:113
u._handleAsync @ index.js:100
(anonymous) @ index.js:84
setTimeout (async)
r.await @ stoplight.js:32
u.sendAsync @ index.js:77
s.send @ index.js:129
d @ index.js:542
a @ index.js:563
b._executeMethod @ index.js:798
(anonymous) @ generateClass.js:36
c @ generateClass.js:65
(anonymous) @ generateClass.js:89
r.(anonymous function) @ generateClass.js:112
(anonymous) @ MyMilestones.jsx:425
Promise.then (async)
(anonymous) @ MyMilestones.jsx:421
Promise.then (async)
(anonymous) @ MyMilestones.jsx:389
Promise.then (async)
(anonymous) @ MyMilestones.jsx:382
c @ middleware.jsx:76
value @ MyMilestones.jsx:381
onClick @ MyMilestones.jsx:897
f @ ReactErrorUtils.js:24
i @ EventPluginUtils.js:83
executeDispatchesInOrder @ EventPluginUtils.js:106
d @ EventPluginHub.js:41
l @ EventPluginHub.js:52
e.exports @ forEachAccumulated.js:22
processEventQueue @ EventPluginHub.js:250
(anonymous) @ ReactEventEmitterMixin.js:15
handleTopLevel @ ReactEventEmitterMixin.js:25
l @ ReactEventListener.js:70
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
WebSocketSubProvider.js:25 RPC Error Response Error: connection not open
    at o.send (index.js:219)
    at t.value (WebSocketSubProvider.js:33)
    at t (index.js:113)
    at l.handleRequest (hooked-wallet.js:197)
    at t (index.js:113)
    at t.value (GasPriceProvider.js:17)
    at t (index.js:113)
    at e.exports.handleRequest (inflight-cache.js:30)
    at t (index.js:113)
    at c.handleRequest (filters.js:88)
    at t (index.js:113)
    at o.handleRequest (sanitizer.js:27)
    at t (index.js:113)
    at s.handleRequest (nonce-tracker.js:79)
    at t (index.js:113)
    at i.r.handleRequest (fixture.js:26) undefined
(anonymous) @ WebSocketSubProvider.js:25
o.send @ index.js:219
value @ WebSocketSubProvider.js:33
t @ index.js:113
l.handleRequest @ hooked-wallet.js:197
t @ index.js:113
value @ GasPriceProvider.js:17
t @ index.js:113
handleRequest @ inflight-cache.js:30
t @ index.js:113
c.handleRequest @ filters.js:88
t @ index.js:113
o.handleRequest @ sanitizer.js:27
t @ index.js:113
s.handleRequest @ nonce-tracker.js:79
t @ index.js:113
r.handleRequest @ fixture.js:26
t @ index.js:113
value @ CleanserSubProvider.js:16
t @ index.js:113
u._handleAsync @ index.js:100
(anonymous) @ index.js:84
setTimeout (async)
r.await @ stoplight.js:32
u.sendAsync @ index.js:77
s.send @ index.js:129
d @ index.js:542
a @ index.js:563
b._executeMethod @ index.js:798
(anonymous) @ generateClass.js:36
c @ generateClass.js:65
(anonymous) @ generateClass.js:89
r.(anonymous function) @ generateClass.js:112
(anonymous) @ MyMilestones.jsx:425
Promise.then (async)
(anonymous) @ MyMilestones.jsx:421
Promise.then (async)
(anonymous) @ MyMilestones.jsx:389
Promise.then (async)
(anonymous) @ MyMilestones.jsx:382
c @ middleware.jsx:76
value @ MyMilestones.jsx:381
onClick @ MyMilestones.jsx:897
f @ ReactErrorUtils.js:24
i @ EventPluginUtils.js:83
executeDispatchesInOrder @ EventPluginUtils.js:106
d @ EventPluginHub.js:41
l @ EventPluginHub.js:52
e.exports @ forEachAccumulated.js:22
processEventQueue @ EventPluginHub.js:250
(anonymous) @ ReactEventEmitterMixin.js:15
handleTopLevel @ ReactEventEmitterMixin.js:25
l @ ReactEventListener.js:70
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
MyMilestones.jsx:449 Error: connection not open
    at o.send (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3144216)
    at t.value (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3530991)
    at t (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3396501)
    at l.handleRequest (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3458584)
    at t (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3396501)
    at t.value (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3529743)
    at t (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3396501)
    at e.exports.handleRequest (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3527955)
    at t (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3396501)
    at c.handleRequest (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3500176)
    at t (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3396501)
    at o.handleRequest (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3528397)
    at t (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3396501)
    at s.handleRequest (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3490915)
    at t (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3396501)
    at i.r.handleRequest (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3489064)
From previous event:
    at P.R [as _captureStackTrace] (https://alpha.giveth.io/static/js/main.559d3fba.js:1:1432486)
    at P._resolveFromExecutor (https://alpha.giveth.io/static/js/main.559d3fba.js:1:1460445)
    at new P (https://alpha.giveth.io/static/js/main.559d3fba.js:1:1453901)
    at r (https://alpha.giveth.io/static/js/main.559d3fba.js:1:412702)
    at a (https://alpha.giveth.io/static/js/main.559d3fba.js:1:218860)
    at Object.b._executeMethod (https://alpha.giveth.io/static/js/main.559d3fba.js:1:3188449)
    at https://alpha.giveth.io/static/js/main.559d3fba.js:1:194475
    at c (https://alpha.giveth.io/static/js/main.559d3fba.js:1:194563)
    at https://alpha.giveth.io/static/js/main.559d3fba.js:1:195580
    at a.r.(anonymous function) [as acceptMilestone] (https://alpha.giveth.io/static/js/main.559d3fba.js:1:195592)
    at https://alpha.giveth.io/static/js/main.559d3fba.js:1:3706273

**Comment by vojtechsimetka** [comment]
Do you by any chance have a slow connection? Sou are being disconnected from feathers. Refreshing should fix the problem.

**Comment by GriffGreen** [comment]
I def have horribly slow internet. Will try again at a cafe.

**Comment by GriffGreen** [comment]
It worked! Just bad wifi connection, good to know! Thx!!!

**Comment by vojtechsimetka** [comment]
Yeah it is something that will have to be addressed, I'll create an issue for it.
