### ISSUE TITLE
reproposing button for rejected milestone does not work 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#573]
1)  Editing [this Milestone which @GriffGreen rejected by accident](https://beta.giveth.io/campaigns/5b5b38b19737b23ee71c73a6/milestones/5c0ea28e06392d786b64d4ad) directly from the link threw a constant error (bug report content below)

2) When clicking the button 'repropose' under rejected Milestones simply nothing happens.

3) I then tried clicking the edit button here to see if I could repropose their (nope), so wanted to navigate away. On doing so I got a mention of unsaved changes. Upon saving the Milestone disappeared from rejected Milestones. It is now .. nowhere :) 

Bug report of the initial editing: 

```
`Description` of the Error: 
      Sadly we were unable to load the requested milestone details. Please try again. 
      Error name: 
      Cast to ObjectId failed for value "undefined" at path "_id" for model "milestone" 
      
      Error lineNumber: 
      undefined 
      
      Error fileName: 
      undefined
```
      
      Error stack: 
      Error: Cast to ObjectId failed for value "undefined" at path "_id" for model "milestone" 
    at convert (https://beta.giveth.io/static/js/main.a4327bdf.js:1:76703) 
    at r.<anonymous> (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1681737) 
    at r.onack (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1748521) 
    at r.onpacket (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1747927) 
    at r.<anonymous> (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1749978) 
    at r.emit (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1702284) 
    at r.ondecoded (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1708340) 
    at o.<anonymous> (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1749978) 
    at o.r.emit (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1702284) 
    at o.add (https://beta.giveth.io/static/js/main.a4327bdf.js:1:1700627)

**Comment by perissology** [comment]
this was fixed at some point
