### ISSUE TITLE
error message when delegating

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#577]
When I delegate funds I get the below error message.
When pressing the delegate button I also do not get a sign the transaction message or a pop-up from metamask (I do see the '1' popping up in the extension)

![image](https://user-images.githubusercontent.com/6533925/49976659-21d06f80-ff43-11e8-84d0-24a135f78cf1.png)

**Comment by krrisis** [comment]
To make it clear, the delegation DOES work now, just gives that message.

**Comment by GriffGreen** [comment]
I am now getting the same issue... 

<img width="1280" alt="screen shot 2018-12-19 at 6 04 05 am" src="https://user-images.githubusercontent.com/14945613/50200083-9dbc2480-0354-11e9-8bc7-bbf5f732fdf6.png">

The console error there happens when loading the page, before taking the action, so there is no console error logged, butthe log being reported via email is: 

      Description of the Error:
      Unable to update the donation in feathers

      Error name:
      donations validation failed: ownerType: Path `ownerType` is required.
      
      Error lineNumber:
      undefined
      
      Error fileName:
      undefined
      
      Error stack:
      BadRequest: donations validation failed: ownerType: Path `ownerType` is required.
    at new s (https://beta.giveth.io/static/js/main.d06ff858.js:1:74773)
    at convert (https://beta.giveth.io/static/js/main.d06ff858.js:1:76865)
    at r.<anonymous> (https://beta.giveth.io/static/js/main.d06ff858.js:1:1695530)
    at r.onack (https://beta.giveth.io/static/js/main.d06ff858.js:1:1762314)
    at r.onpacket (https://beta.giveth.io/static/js/main.d06ff858.js:1:1761720)
    at r.<anonymous> (https://beta.giveth.io/static/js/main.d06ff858.js:1:1763771)
    at r.emit (https://beta.giveth.io/static/js/main.d06ff858.js:1:1716077)
    at r.ondecoded (https://beta.giveth.io/static/js/main.d06ff858.js:1:1722133)
    at o.<anonymous> (https://beta.giveth.io/static/js/main.d06ff858.js:1:1763771)
    at o.r.emit (https://beta.giveth.io/static/js/main.d06ff858.js:1:1716077)

**Comment by perissology** [comment]
fixed in ea2dd7691e1d6e4af5b05c0ae1d5ac1b856239d8
