### ISSUE TITLE
Cannot read property 'toString' of undefined when using Frame

### ISSUE THREAD

**Issue by jvluso** [Giveth/giveth-dapp#601]
Using [Frame](https://github.com/floating/frame) instead of Metamask has worked in the past, but it is currently throwing the following error. I'm not sure if this is because of Frame or because of Giveth. Do you know what function is returning undefined that shouldn't be?

```
There has been an error in the DApp.
Details
Error message:
Cannot read property 'toString' of undefined

Component stack:

    in t
    in R
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in t
    in t

Error lineNumber:
Error fileName:
Error stack:
TypeError: Cannot read property 'toString' of undefined
    at t.value (https://beta.giveth.io/static/js/main.923b0f6a.js:1:540956)
    at t.value (https://beta.giveth.io/static/js/main.923b0f6a.js:1:545376)
    at Co (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1152461)
    at No (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1157376)
    at pi (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1166967)
    at hi (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1167274)
    at $i (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1170824)
    at Yi (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1170336)
    at Wi (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1170162)
    at Hi (https://beta.giveth.io/static/js/main.923b0f6a.js:1:1169535)
```

**Comment by perissology** [comment]
the error appears to be the same issue as #586.

However I think a different fix will need to be applied. It appears the dapp is not detecting the frame provider. The current implementation was only tested with metamask, and I'm 90% sure there will be issues w/ other providers.

The main issue point would be detecting the the provider is enabled or not. https://github.com/Giveth/giveth-dapp/blob/develop/src/contextProviders/Web3Provider.jsx#L123.
I don't think it would be very difficult to come up w/ a solution, however last I checked there was no standard on this.

**Comment by perissology** [comment]
can you try using develop.giveth.io to see if you still get the 'toString()' error?

**Comment by jvluso** [comment]
I see the error on beta with the extension
I see the error on develop with the extension
I see the error on beta without the extension
I don't see the error on develop without the extension

**Comment by jvluso** [comment]
The issue was not on Giveth's end - it was a versioning issue with Frame. Thank you for helping me find it.
