### ISSUE TITLE
beta.giveth.io/my-milestones - DApp error - page crashes

### ISSUE THREAD

**Issue by mroberts10** [Giveth/giveth-dapp#630]
I get the following error message

"There has been an error in the DApp.
Details
Error message:
[number-to-bn] while converting number "2.1e+21" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.

Component stack:

    in t
    in t
    in t
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in t
    in t

Error lineNumber:
Error fileName:
Error stack:
Error: [number-to-bn] while converting number "2.1e+21" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.
    at e.exports (https://beta.giveth.io/static/js/main.65cbb292.js:1:467344)
    at Object.fromWei (https://beta.giveth.io/static/js/main.65cbb292.js:1:601895)
    at Object.fromWei (https://beta.giveth.io/static/js/main.65cbb292.js:1:173890)
    at k (https://beta.giveth.io/static/js/main.65cbb292.js:1:21803)
    at https://beta.giveth.io/static/js/main.65cbb292.js:1:3523055
    at Array.map (<anonymous>)
    at https://beta.giveth.io/static/js/main.65cbb292.js:1:3517379
    at No (https://beta.giveth.io/static/js/main.65cbb292.js:1:1160746)
    at pi (https://beta.giveth.io/static/js/main.65cbb292.js:1:1167687)
    at hi (https://beta.giveth.io/static/js/main.65cbb292.js:1:1167994)"

**Comment by perissology** [comment]
this is probably fixed in the current release branch

**Comment by perissology** [comment]
related #633. fixed in 7598b3f5955105a43364dc02b9d771a088294c01
