### ISSUE TITLE
When multiple expenses in DAI = error when attaching proof 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#637]
Reproduce: 

- Select 'Raising funds in DAI' as a currency, 
- Hit 'add multiple expenses' 
- Click 'attach proof'

At this moment: the DApp throws the below error: 

There has been an error in the DApp.
Details
Error message:
this.state.conversionRate.timestamp.toFixed is not a function

Component stack:

    in t
    in n
    in form
    in Formsy
    in t
    in t
    in div
    in div
    in t
    in t
    in t
    in n
    in div
    in t
    in form
    in Formsy
    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in n
    in t
    in t
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in t
    in t

Error lineNumber:
Error fileName:
Error stack:
TypeError: this.state.conversionRate.timestamp.toFixed is not a function
    at t.value (https://beta.giveth.io/static/js/main.ab446371.js:1:3124984)
    at Po (https://beta.giveth.io/static/js/main.ab446371.js:1:1199701)
    at No (https://beta.giveth.io/static/js/main.ab446371.js:1:1204616)
    at pi (https://beta.giveth.io/static/js/main.ab446371.js:1:1214207)
    at hi (https://beta.giveth.io/static/js/main.ab446371.js:1:1214514)
    at $i (https://beta.giveth.io/static/js/main.ab446371.js:1:1218064)
    at Yi (https://beta.giveth.io/static/js/main.ab446371.js:1:1217576)
    at Wi (https://beta.giveth.io/static/js/main.ab446371.js:1:1217402)
    at Hi (https://beta.giveth.io/static/js/main.ab446371.js:1:1216775)
    at vi (https://beta.giveth.io/static/js/main.ab446371.js:1:1216007)

 
Propose milestone?
The milestone will be proposed to the campaign owner and he or she might approve or reject your milestone.
Cancel    Yes, propose

**Comment by perissology** [comment]
fixed in cb16d5057fba7b95c89761d0866d0008ba9b8856
